name: "trading_simulation_batch"

deephaven:
  connection_url: "${DH_CONNECTION_URL}"
  auth_method: "password"
  username: "${DH_USERNAME}"
  password: "${DH_PASSWORD}"
  
execution:
  worker_script: "trading_simulation_batch.py"
  num_partitions: 2
  max_concurrent_sessions: 10
  heap_size_gb: 16.0
  script_language: "Python"

batch:
  timeout_minutes: 60

dates:
  start: "2024-01-01"
  end: "2024-12-31"
  weekdays_only: true
  
env:
  OUTPUT_NAMESPACE: "ExampleBatchTradingSim"
  MAX_POSITION_DOLLARS: "10000"
  EMA_DECAY_TIME: "PT00:01:00"
  LOT_SIZE: "100"
