name: "trading_simulation"

deephaven:
  connection_url: "${DH_CONNECTION_URL}"
  auth_method: "password"
  username: "${DH_USERNAME}"
  password: "${DH_PASSWORD}"
  
execution:
  worker_script: "trading_simulation.py"
  num_partitions: 2
  max_concurrent_sessions: 10
  
replay:
  heap_size_gb: 16.0
  init_timeout_minutes: 30
  script_language: "Python"
  replay_start: "09:30:00"
  replay_speed: 100.0
  replay_timestamp_columns:
    - namespace: "FeedOS"
      table: "EquityQuoteL1"
      column: "Timestamp"

dates:
  start: "2024-01-01"
  end: "2024-01-31"
  weekdays_only: true
  
env:
  OUTPUT_NAMESPACE: "ExampleReplayTradingSim"
  MAX_POSITION_DOLLARS: "10000"
  EMA_DECAY_TIME: "PT00:01:00"
  LOT_SIZE: "100"
